
name: Deploy to GitHub Pages and Notify Discord

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

      - name: Send Discord notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -H "Content-Type: application/json" -d "{
            \"content\": \"There has been an update to the documents!\\n\\n**Notes:**\\n${{ env.COMMIT_MESSAGE }}\\n\\nhttps://deveyus.github.io/antique-aether/AntiqueAetherNotes\"
          }" "$DISCORD_WEBHOOK"
